blank_issues_enabled: false
contact_links:
  - name: ❤️ Morph Community support
    url: https://github.com/morph-data/morph/discussions
    about: Please ask and answer questions here.
  - name: 📖 Morph documentation
    url: https://docs.morph-data.io/
    about: Learn more about how to use Morph